### ISSUE TITLE
run step executed at specified times/steps only

### ISSUE THREAD

**Issue by jeanbraun** [benbovy/xarray-simlab#134]
Hello @benbovy. Is it possible to perform a run_step only at times/steps specified by a given clock? As an example, I need to compute an analytical solution to compare to a numerical solution. It is quite computationally demanding so I only want to compute it at the time steps given by an "out" clock and not the master clock.

**Comment by benbovy** [comment]
Yes, it is possible, using [on_demand](https://xarray-simlab.readthedocs.io/en/latest/_api_generated/xsimlab.on_demand.html#xsimlab.on_demand) variables.

Those variables have their own method, decorated with ``@my_var.compute``, so each time they are accessed as attribute, the code within those methods is executed and a value is returned.

Then you could add those variables as ``output_vars`` of [xsimlab.create_setup](https://xarray-simlab.readthedocs.io/en/latest/_api_generated/xsimlab.create_setup.html#xsimlab.create_setup) or [Dataset.xsimlab.update_vars](https://xarray-simlab.readthedocs.io/en/latest/_api_generated/xarray.Dataset.xsimlab.update_vars.html#xarray.Dataset.xsimlab.update_vars) with any clock coordinate or ``None``.

There is an example [here](https://github.com/fastscape-lem/fastscape/blob/ab1b13af08a1b20296ff5fa92610aab19ee5796e/fastscape/processes/main.py#L153-L190).

**Comment by benbovy** [comment]
@jeanbraun does `on_demand` variables fit your use case?

I'm going to close this issue, but feel free to re-open it if that's not the case.
