### ISSUE TITLE
`group_dict` variable

### ISSUE THREAD

**Issue by benbovy** [benbovy/xarray-simlab#140]
`xsimlab.group_dict()` variable would be like to `xsimlab.group()`, but instead of iterating over the values only, it would provide dict-like access where keys are 2-length tuples ('process_name', 'variable_name').

**Comment by benbovy** [comment]
One problem is that 'process_name' is not known before creating a `xsimlab.Model` object...

**Comment by eho-tacc** [comment]
+1 to this feature, even if `process_name` is not included in the dict. For my particular use case (N-D `DataArray` construction), I think it would be really useful to expose variable metadata in the `group` (and generally across the package, but that's a different point):

```python
@xs.process
class CoordsX:
    x = xs.index(groups=['coords'], dims='x')
    
    def initialize(self):
        self.x = range(3)

@xs.process
class CoordsY:
    y = xs.index(groups=['coords'], dims='y')
    
    def initialize(self):
        self.y = range(5)
        
@xs.process
class InitArray:
    DIMS = ('x', 'y')
    
    arr = xs.variable(dims=DIMS, intent='out')
    coords = xs.group('coords')
    
    def initialize(self):
        self.arr = xr.DataArray(
            data=0.,
            dims=self.DIMS,
            # Attribute.name in this instance
            coords={k: self.coords[k] for k in self.DIMS}
        )
```

My suboptimal workaround has been to use `xs.utils.variables_dict(CoordsY)['y']` to retrieve metadata. Apologies in advance if there exists an elegant alternative to this, and thanks for giving us this package!

**Comment by benbovy** [comment]
@eho-tacc your code example made me think about a possible way in #141 to better access variable metadata across the package.
