### ISSUE TITLE
simple xarray-simlab code fail to set attrs attributes.

### ISSUE THREAD

**Issue by luca-penasa** [benbovy/xarray-simlab#51]
trying to run the following code:
```python
import xsimlab as xs
import numpy as np

@xs.process
class TestProcess(object):
    spacing = xs.variable(description='grid spacing', default=2)
        
mod = xs.Model({"proc1": TestProcess})
```

fails with the following error from the attrs's generated init:
```python 
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-8-600a28a8e410> in <module>()
      6     spacing = xs.variable(description='grid spacing', default=2)
      7 
----> 8 mod = xs.Model({"proc1": TestProcess})

~/.local/lib/python3.7/site-packages/xsimlab/model.py in __init__(self, processes)
    357             ensure_process_decorated(cls)
    358 
--> 359         builder = _ModelBuilder(processes)
    360 
    361         builder.bind_processes(self)

~/.local/lib/python3.7/site-packages/xsimlab/model.py in __init__(self, processes_cls)
     42     def __init__(self, processes_cls):
     43         self._processes_cls = processes_cls
---> 44         self._processes_obj = {k: cls() for k, cls in processes_cls.items()}
     45 
     46         self._reverse_lookup = {cls: k for k, cls in processes_cls.items()}

~/.local/lib/python3.7/site-packages/xsimlab/model.py in <dictcomp>(.0)
     42     def __init__(self, processes_cls):
     43         self._processes_cls = processes_cls
---> 44         self._processes_obj = {k: cls() for k, cls in processes_cls.items()}
     45 
     46         self._reverse_lookup = {cls: k for k, cls in processes_cls.items()}

<attrs generated init c3bfe1a9beca995748daa500465cd5be1c8546d3> in __init__(self)
      1 def __init__(self, ):
----> 2     self.spacing = attr_dict['spacing'].default
      3     self.__attrs_post_init__()

AttributeError: can't set attribute
```

I tested various tagged version of both xarray-simlab and attrs, any idea of what might be wrong? 

BTW I am working on setting up a large scale simulation so I was considering using this package for initializing/keeping track of all the parameters, although the actual modelling in  the time-domain will be executed by external code. Thus I'd like to use xarray-simlab mostly for the smart variable method and to create the experimental setup in discrete steps. Is there any problem I could find in only calling the model.initialize() method ? or e.g not passing clocks to the builder?

thank you very much.
this seems a very useful project. Hope I could contribute anything.
luca p

**Comment by luca-penasa** [comment]
brief update after some research, maybe it might help. It seems the following code:

```python
import xsimlab as xs
from xsimlab.variable import _as_dim_tuple, VarIntent, VarType
import attr

def variable(dims=(), intent='in', group=None, default=attr.NOTHING,
             validator=None, description='', attrs=None):


    
    metadata = {
        'var_type': VarType.VARIABLE,
                'dims': _as_dim_tuple(dims),
                'intent': VarIntent(intent),
                'group': group,
                'attrs': attrs or {},
                'description': description}

    return attr.attrib(metadata=metadata, default=default, validator=validator,
                       init=False, cmp=False, repr=False)

import attr
@xs.process
class test(object):
    spacing = variable(description='grid spacing', default=2)
    
t = test()
```

does not work bu this does (only the key of the metadata dict is changed):

```python 
import xsimlab as xs
from xsimlab.variable import _as_dim_tuple, VarIntent, VarType
import attr

def variable(dims=(), intent='in', group=None, default=attr.NOTHING,
             validator=None, description='', attrs=None):


    
    metadata = {
        'var_type2': VarType.VARIABLE,
                'dims': _as_dim_tuple(dims),
                'intent': VarIntent(intent),
                'group': group,
                'attrs': attrs or {},
                'description': description}

    return attr.attrib(metadata=metadata, default=default, validator=validator,
                       init=False, cmp=False, repr=False)

import attr
@xs.process
class test(object):
    spacing = variable(description='grid spacing', default=2)
    
t = test()
```

**Comment by luca-penasa** [comment]
Last comment was not very useful, but I've been trying to investigate the issue better.
here is what I discovered (btw I am on current git version), but I'd really appreciate some devs input:
- in my first comment I was trying to set a default value. this is causing an error during class initialization because the self.__attrs_post_init__(), which reads, from process.py:
```python
    def init_process(self):
        self.__xsimlab_model__ = None
        self.__xsimlab_name__ = None
        self.__xsimlab_store__ = None
        self.__xsimlab_store_keys__ = {}
        self.__xsimlab_od_keys__ = {}
```
is called  __at the end__ of the __init__ of the class, thus after the init tries to set the default values. This means that the store and the store_keys does not exists yet (until attrs_post_init is called). this is clear from the error above:
```python
----> 2     self.spacing = attr_dict['spacing'].default
      3     self.__attrs_post_init__()
```
the error happens at 2 because self.__attrs_post_init__() is still to be called.

- the store and the store keys are used by the property responsible for managing the get/set of the variable value, from process.py [ln 250 ca.]

```python
property(fget=get_from_store, fset=put_in_store, doc=var_doc)
```

and thus they need to exists before setting and getting the values.
But when put_in_store is called (e.g. to set the default value) the   self.__xsimlab_store__ and  self.__xsimlab_store_keys__ still does not exists.

- when __not__ using a default value still some problems persists because init_process, which is called at the end of __init__ set up a __None__ store as self.__xsimlab_store__. Thus not allowing to set/get any value from it.

- A simple solution is to modify the post init method as:
```python
    def init_process(self):
        self.__xsimlab_model__ = None
        self.__xsimlab_name__ = None
        self.__xsimlab_store__ = {} # a default store 
        self.__xsimlab_store_keys__ = {}
        self.__xsimlab_od_keys__ = {}
```
this still does not solve the problem with the default values of the variables which are set when this method is still to be called.

I'd really appreciate some input from the developers... thanks
luca

**Comment by luca-penasa** [comment]
after a lot of trial and errors I ended up by these considerations:
- default values support in variables is broken. in fact there is no test using a default value
- I would suggest to move the default value to the metadata associated to the variable, so that can be used e.g. when updating the variables, in the case a value for that var is not provided.

**Comment by benbovy** [comment]
Many thanks for this detailed report @luca-penasa ! And sorry for the delay.

> default values support in variables is broken. in fact there is no test using a default value

Actually, support for default values is not yet fully implemented! I admit it wasn't a good idea to already add the ``default`` argument in ``xs.variable()``! I didn't expected that this would cause issues like this, sorry! For now we should really leave ``default=attr.NOTHING``.

> I would suggest to move the default value to the metadata associated to the variable

Do you mean something like ``xs.variable(attrs={'default': 2})``? The ``attrs``argument is rather for holding user custom metadata. If we support default values, it should still be set using a reserved keyword argument IMO.

Or maybe you mean moving the default value to the metadata attribute of the underlying ``attr.attrib``? Like this: 

```python
def variable(dims=(), intent='in', group=None, default=attr.NOTHING,
             validator=None, description='', attrs=None):
  
    metadata = {'default_value': default, ...}

    return attr.attrib(metadata=metadata, validator=validator,
                       init=False, cmp=False, repr=False)
```

Unless there is a way to handle ``attr.attrib(default)`` so that we can avoid the issue here, I think that this solution above is the best one. 

xarray-simlab uses attrs in a rather uncommon way. For example, ``xs.process`` decorated classes turn all declared variables into properties, so is not always possible just reusing the features of attrs that are related to instance initialization.

But in this case, there no need to do something special with the default value in a process class ``__init__``. Process classes are used here just as holders of some useful metadata about their declared parameters/variables. The logic of setting the default value of a variable, e.g., in a ``xarray.Dataset`` or  in ``__xsimlab_store__`` is implemented elsewhere and executed after a ``xs.Model`` object has been created (i.e., after Process classes have been instantiated).

**Comment by benbovy** [comment]
> BTW I am working on setting up a large scale simulation so I was considering using this package for initializing/keeping track of all the parameters, although the actual modelling in the time-domain will be executed by external code. Thus I'd like to use xarray-simlab mostly for the smart variable method and to create the experimental setup in discrete steps. Is there any problem I could find in only calling the model.initialize() method ? or e.g not passing clocks to the builder?

I don't see anything that will prevent you doing that, but I might be wrong. However, I think that you will still need to set a (dummy) clock with ``create_setup``. It is required, but in your case it would just run an empty loop during the simulation.

Actually, I've thinking a bit about the possibility of setting custom execution workflows, i.e., not tied to the rigid ``initialize->clock*(run_step->finalize_step)->finalize``. This would require a fair amount of work, though.

> this seems a very useful project. Hope I could contribute anything.

This would be greatly appreciated! :-)

**Comment by luca-penasa** [comment]
> Many thanks for this detailed report @luca-penasa ! And sorry for the delay.
> 
> > default values support in variables is broken. in fact there is no test using a default value
> 
> Actually, support for default values is not yet fully implemented! I admit it wasn't a good idea to already add the `default` argument in `xs.variable()`! I didn't expect that this would cause issues like this, sorry! For now we should really leave `default=attr.NOTHING`.
> 
> > I would suggest to move the default value to the metadata associated to the variable
> 
> Do you mean something like `xs.variable(attrs={'default': 2})`? The `attrs`argument is rather for holding user custom metadata. If we support default values, it should still be set using a reserved keyword argument IMO.
> 
> Or maybe you mean moving the default value to the metadata attribute of the underlying `attr.attrib`? Like this:
yest that was what I m
> 
> ```python
> def variable(dims=(), intent='in', group=None, default=attr.NOTHING,
>              validator=None, description='', attrs=None):
>   
>     metadata = {'default_value': default, ...}
> 
>     return attr.attrib(metadata=metadata, validator=validator,
>                        init=False, cmp=False, repr=False)
> ```
> 
> Unless there is a way to handle `attr.attrib(default)` so that we can avoid the issue here, I think that this solution above is the best one.
> 
> xarray-simlab uses attrs in a rather uncommon way. For example, `xs.process` decorated classes turn all declared variables into properties, so is not always possible just reusing the features of attrs that are related to instance initialization.
> 
> But in this case, there no need to do something special with the default value in a process class `__init__`. Process classes are used here just as holders of some useful metadata about their declared parameters/variables. The logic of setting the default value of a variable, e.g., in a `xarray.Dataset` or in `__xsimlab_store__` is implemented elsewhere and executed after a `xs.Model` object has been created (i.e., after Process classes have been instantiated).

**Comment by luca-penasa** [comment]
thank you @benbovy .
Now I've got a little better the architecture... and can understand it was meant to work like that.

I am actually trying to replicate a similar structure for my project. One of the major deal breaking for me was the impossibility to deal with "nested"  variables: a process defines a new variable in the form of a a complex object. that object might in turn contain attributes that should be treated as variables themselves. 
i.e. in psudopythoncode

```python
@process
class Process1:
    var1 = variable (...) [instance of Var1]
```

with  Var1, something like

```python
@attr.attrs [or process]
class Var1:
    v1 = @attr.ib [or variable](...)
    v2 = @attr.ib [or variable](...)
    v3 = @attr.ib [or variable](...)
    v4 = @attr.ib [or variable](...)
```
in a different process i might need to access by reading or writing one of these nested variables. As it is structured now I think it is possible to only access the var1 object defined in the different process, like this:

```python
@process
class Process2:
    var1_imported = foreign variable from Process1(...) [instance of Var1]
```
in this case I can import within Process2 var1 as a foreign variable. But then I cannot keep a record of what attribute is actually changes in var1 - e.g. v1? or v2? all of them?

would be more useful to be able to import nested variables. e.g. something like:

```python
@process
class Process2:
    v1_imported = "Process1.var1.v1" as foreign variable from Process1(...) 
```

depending on how I define the variable I can track whether the variable is read/write etc.

The main problem I see now is the structure of the store as a non-nested dict as it is implemented now. Thus I am not sure how I could improve xsimlab to deal with this.... maybe you thought about this? any idea?

My interest is basically in keeping track where a variable is set/updated/read in the model by which module, etc which is the same idea behind xsimlab as far as I got....

btw nice to see such a good earth-scientist pythonist!
thank you very much for help

best,
luca

**Comment by benbovy** [comment]
Using flat collections of variables or processes was a design choice. Nested structures would greatly complicate the implementation and doesn't play well with the xarray data model (I initially started this project with the goal to use xarray objects as simulation I/O). For example, how to define ``intent`` for a complex object having multiple attributes (or a foreign variable linked to that complex object)?

Looking at your example, would it be a problem to have three process classes like below?

```python
@xs.process
class Var1:
    v1 = xs.variable()
    v2 = xs.variable()
    v3 = xs.variable()
    v4 = xs.variable()

@xs.process
class Process1:
    ref_v1 = xs.foreign(Var1, 'v1')
    ref_v2 = xs.foreign(Var1, 'v2')
    ref_v3 = xs.foreign(Var1, 'v3')
    ref_v4 = xs.foreign(Var1, 'v4')

@xs.process
class Process2:
    ref_v1 = xs.foreign(Var1, 'v1')

```

You can actually create a process class as a "variable bundle", i.e., just for declaring some variables (no methods),  like ``Var1`` above. The downside is that if you want to use those variables in other process classes, you need to declare a ``foreign`` for each of them (like in ``Process1``), which is a bit tedious. #37 solves this, but only partially (not possible to track which specific variable is read and shouldn't be used to set values).

>  btw nice to see such a good earth-scientist pythonist!

Thanks :-)

**Comment by luca-penasa** [comment]
just to update you, after some thinking, what about using a nested variables scheme like
```python
@xs.process
class Process1:
    ref_v1 = xs.foreign(Var1, 'v1.v2.v3')
```

simplified working implementation here (I am not using a store like in xsimlab):
https://gist.github.com/luca-penasa/89e3ad12ca80d597e0cf14a0a0cff06c

but i don't know how well it could work with the current implementation and how much work one should do to make this work.

variables imported with this nested scheme could just live where they are... in fact they would be yet in the store given the object containing them is. [I also don't know how xsimlab would react to storing objects in variables...]

btw I think the store is good but it would definitively better to leave that as an option.
thanks for your help
luca

**Comment by benbovy** [comment]
What about something like: 

```python
@xs.process
class Process1:
    ref_v1 = xs.foreign(Var1, 'v1')
    ref_v2 = xs.foreign(Var1, 'v2')
    ref_v3 = xs.foreign(Var1, 'v3')
```

Do I miss any real advantage of using a nested scheme over explicit declaration of each attribute (apart from maybe being a little bit more succinct)?

I'm quite reluctant to add support for nested variables for several reasons:

- This would add too much complexity to the (already quite complex) current implementation in many places, which is not worth of the benefits IMHO.
- We would need to extend API support for many things, e.g.,  ``xs.foreign(Var1, ('v1', 'v2', 'v3'), intent={'v1': 'in', 'v2': 'in', 'v3': 'out'})``. For ``xs.variable`` the same kind of dictionary should be needed for specifying ``dims`` or later default values, validators, etc. At the end the code is not really shorter, it's even less readable.
- I'm slightly concerned by the overhead this would add when getting/setting the values of the variables in process classes through their properties.
- Nested variables don't play well with the xarray data model. The current one-to-one relationship between a``xs.variable`` and a ``xarray.Variable`` is easy to deal with. Maintaining both one-to-one and one-to-many relationships in the case of nested variables is hard to maintain. We could argue the same for other kinds of automated I/O interfaces that we could later support, like command-line (options or input file entries) or UI (widgets). Storing complex objects (i.e., other than arrays or primitive types) as ``xs.variable`` values wouldn't play well with those I/O interfaces either.

Without taking statements from "The Zen of Python" too religiously, I think that the "flat is better than nested" principle rather applies well here.

**Comment by benbovy** [comment]
> btw I think the store is good but it would definitively better to leave that as an option.

Storing values of process variables directly as class attributes would certainly avoid issues like the one you've reported here. However, properties have also another advantage than using a centralized, abstract store for simulation data: it allows some safe guards, e.g., add read-only properties for variables declared with ``intent='in'``.

**Comment by benbovy** [comment]
First of all, it is always interesting to see for which problems people'd like to use xarray-simlab. This is still a young project with much room for improvement, feedback is very welcomed. So thanks for your feedback and for sharing your use case!

I agree that it is currently not straightforward to wrap existing code with xarray-simlab, or at-least it is not very clear (or still undocumented) how this could be done.

That said, I think that your use case is not incompatible with xarray-simlab (how it is working currently). You don't need to refactor your object-oriented code, but you'd need to write some wrapper code in ``xs.process`` classes, using composition.

I've uploaded a example similar to what you describe, but very simplified. Hopefully you'll find it helpful:

https://gist.github.com/benbovy/2bb908c745657712e1da213c0a9badd9

As you can see, it's actually possible to declare ``xs.variable`` for complex objects (or object collections) and make references to those objects in other process classes with ``xs.foreign``. What you need is also to declare some other ``xs.variable`` that expose one or more attributes of those objects because (1) you want to use them as I/O of your processing and/or (2) these determine the workflow (the order of processes). This can all be done without nested variables.

Note that the the term simulation "store" is a bit misleading here. It is not a container that holds all simulation data but it rather gathers all references to the data that is useful to share between process classes and/or as I/O. Currently it is a simple dictionary accepting any kind of value. We could later support on-disk or distributed stores, which will still work if your objects are serializable.

**Comment by luca-penasa** [comment]
super!
thank you very much. I also did not investigated much the use of on_demand variables. I'll have a look at them.

thank you again!
